### ISSUE TITLE
Getting Error: spawn ENOTDIR with activeWindow()

### ISSUE THREAD

**Issue by sidh01** [sindresorhus/get-windows#185]

**Comment by Ladvace** [comment]
same problem here, did you find a solution?

**Comment by qualwebs** [comment]
@Ladvace @sidh01 Anyone find the solution?

**Comment by Ladvace** [comment]
nope, I get this error on macos, not sure if it's supposed to ask for permissions or the user need to set it manually (didn't try this yet)

**Comment by qualwebs** [comment]
@Ladvace The app is working fine using electron start but not with the build, Not sure if the terminal has the permissions.

BTW, what you are building with this?

**Comment by Ladvace** [comment]
Electron-builder

**Comment by Ladvace** [comment]
same for me, you mean what I'm using to build it?

**Comment by qualwebs** [comment]
No, I mean what purpose you're using this package?

**Comment by Ladvace** [comment]
how is this related to he problem?

**Comment by Nantris** [comment]
Filing a bug report for a native dependency without even specifying the OS is just asking to never get it addressed.

**Comment by qualwebs** [comment]
@Nantris It's in MacOS(Silicon chip), and happening when creating build, Dev mode with electron is working fine.

**Comment by Nantris** [comment]
@qualwebs did you see this? https://github.com/sindresorhus/get-windows/issues/99#issuecomment-870874546

If this fixes the issue, there probably needs to be a note in the README for macOS too.

**Comment by Ladvace** [comment]
> @qualwebs did you see this? [#99 (comment)](https://github.com/sindresorhus/get-windows/issues/99#issuecomment-870874546)
> 
> If this fixes the issue, there probably needs to be a note in the README for macOS too.

I just tried this and it doesn't seem to fix it to me

**Comment by Nantris** [comment]
I'm planning to try this myself on macOS tomorrow, though not Silicon. Any other findings at all that might be helpful towards debugging?

**Comment by qualwebs** [comment]
@Nantris 
My macOS version is 14.6.1.
It works perfectly fine with dev mode in electron but not after build.

Also, Can I fetch browser URLs in linux and windows? if not, why and if that can be achieved?

**Comment by Nantris** [comment]
It works for me on macOS 14.5 - but specifically I tested with the optional permissions disabled.

I suspect the app needs to be signed and notarized to work. I can't answer about URLs because we don't need them, sorry.

**Comment by trinhxyz** [comment]
@Nantris - Related to this issue: #189

**Comment by timeowilliams** [comment]
@qualwebs @sidh01 @Ladvace 

I had the same error:

```
Error getting active window: Error: spawn ENOTDIR
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:776:9)
    at execFile (node:child_process:351:17)
    at node:child_process:243:21
    at activeWindow (file:///Applications/deepfocus.app/Contents/Resources/app.asar/node_modules/get-windows/lib/macos.js:38:25)
    at activeWindow (file:///Applications/deepfocus.app/Contents/Resources/app.asar/node_modules/get-windows/index.js:18:10)
    at async Timeout._onTimeout (file:///Applications/deepfocus.app/Contents/Resources/app.asar/out/main/index.js:220:26) {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'spawn'
}
```


I use an M1 Macbook Pro (16GB) & Sonoma 14.5 

What worked for me was modifying the node-modules directly and changing this file: 
`node_modules/get-windows/lib/macos.js
`

Here's the code:

import path from 'node:path';
import {promisify} from 'node:util';
import childProcess from 'node:child_process';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const execFile = promisify(childProcess.execFile);

const isPackaged = process.mainModule?.filename.indexOf('app.asar') !== -1;
const binary = isPackaged
    ? path.join(process.resourcesPath, 'app.asar.unpacked', 'node_modules', 'get-windows', 'main')
    : path.join(__dirname, '../main');

console.log('Binary path:', binary);

if (!fs.existsSync(binary)) {
    console.error('Binary file does not exist:', binary);
    throw new Error('Binary file not found');
}

const parseMac = stdout => {
    try {
        return JSON.parse(stdout);
    } catch (error) {
        console.error(error);
        throw new Error('Error parsing window data');
    }
};

const getArguments = options => {
    if (!options) {
        return [];
    }

    const arguments_ = [];
    if (options.accessibilityPermission === false) {
        arguments_.push('--no-accessibility-permission');
    }

    if (options.screenRecordingPermission === false) {
        arguments_.push('--no-screen-recording-permission');
    }

    return arguments_;
};

export async function activeWindow(options) {
    const {stdout} = await execFile(binary, getArguments(options));
    return parseMac(stdout);
}

export function activeWindowSync(options) {
    const stdout = childProcess.execFileSync(binary, getArguments(options), {encoding: 'utf8'});
    return parseMac(stdout);
}

export async function openWindows(options) {
    const {stdout} = await execFile(binary, [...getArguments(options), '--open-windows-list']);
    return parseMac(stdout);
}

export function openWindowsSync(options) {
    const stdout = childProcess.execFileSync(binary, [...getArguments(options), '--open-windows-list'], {encoding: 'utf8'});
    return parseMac(stdout);
}

Note: some of the logic is meant for use with building an Electron app, but shouldn't be an issue. 


Afterwards, I can get the activeWindow info with no issues. 
`Time spent on Getting Error: spawn ENOTDIR with activeWindow() · Issue #185 · sindresorhus/get-windows: 2m 0s
`

I'm considering raising a PR if this is a more common issue.

**Comment by trinhxyz** [comment]
@timeowilliams - thanks for the tip, could you raise the PR though, I'm curious to see what the fix is?  Also are you using `electron-forge`?

**Comment by timeowilliams** [comment]
@trinhxyz :

https://github.com/Tech-Nest-Ventures/get-windows/blob/main/lib/macos.js

Something similar to this. I use `electron-builder` right now in combination with https://electron-vite.org/

**Comment by Ladvace** [comment]
I'm using `electron-builder` with https://electron-vite.org/ on Macos M1

**Comment by Ladvace** [comment]
I just tried to replace `node_modules/get-windows/lib/macos.js` as @timeowilliams did but I just get the following error:

```
App threw an error during load
Error: Binary file not found
```
 because `path.join(process.resourcesPath, 'app.asar.unpacked', 'node_modules', 'get-windows', 'main')` doesn't exist

**Comment by Ladvace** [comment]
actually building it, I don't get the error, I just get this:

`  stdout: 'get-windows requires the accessibility permission in “System Settings › Privacy & Security › Accessibility”.\n',`

**Comment by Ladvace** [comment]
I can confirm that giving the right permission and the changes from  @timeowilliams, it works!

**Comment by timeowilliams** [comment]
@trinhxyz , 

Ended up straying away quite a bit from this repo, but if you're interested in just using the dependency without having to mess with the code/just install, feel free to use this dependency:

https://github.com/Tech-Nest-Ventures/get-windows

^ Specifically optimized for MacOS at this time.

**Comment by timeowilliams** [comment]
@Ladvace , 

100%! Was using the wrong method. 

Please change this in  `node_modules/get-windows/lib/macos.js`

```js
const isPackaged = process.main?.filename.indexOf("app.asar") !== undefined;
```

to this: 

```js
const isPackaged = process.resourcesPath !== process.cwd();
```

**Comment by Ladvace** [comment]
seems working great now!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/get-windows/pull/192#issuecomment-2374780649
