### ISSUE TITLE
Failed to execute '/Users/devicename/.nvm/versions/node/v18.20.4/bin/node

### ISSUE THREAD

**Issue by sumit3001** [sindresorhus/get-windows#193]
Try to build electron app with get-windows and end up with this error

Mac os version: 14.6.1
electron: 29.3.0,
node:  18.20.4

electron-builder --macos --x64 --arm64 --dir
  • electron-builder  version=24.13.3 os=23.6.0
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=get-windows@9.1.1 platform=darwin arch=x64
  • rebuilding native dependency  name=get-windows version=9.1.1
  ⨯ cannot execute  cause=exit status 1
$ node-pre-gyp install --fallback-to-build
    Failed to execute '/Users/devicename/.nvm/versions/node/v18.20.4/bin/node /Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project//node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project//node_modules/get-windows/lib/binding/napi-9-darwin-unknown-x64/node-get-windows.node --module_name=node-get-windows --module_path=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project//node_modules/get-windows/lib/binding/napi-9-darwin-unknown-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=9 --node_napi_label=napi-v9' (1)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
                    errorOut=node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@1.0.11
    node-pre-gyp info using node@18.20.4 | darwin | arm64
    node-pre-gyp http GET https://github.com/sindresorhus/get-windows/releases/download/v9.1.1/napi-9-darwin-unknown-x64.tar.gz
    node-pre-gyp ERR! install response status 404 Not Found on https://github.com/sindresorhus/get-windows/releases/download/v9.1.1/napi-9-darwin-unknown-x64.tar.gz 
    node-pre-gyp WARN Pre-built binaries not installable for get-windows@9.1.1 and electron@29.4.6 (electron-v29.4 ABI, unknown) (falling back to source compile with node-gyp) 
    node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/sindresorhus/get-windows/releases/download/v9.1.1/napi-9-darwin-unknown-x64.tar.gz 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@7.1.2
    gyp info using node@18.20.4 | darwin | arm64
    gyp info ok 
    gyp info it worked if it ends with ok
    gyp info using node-gyp@7.1.2
    gyp info using node@18.20.4 | darwin | arm64
    gyp info find Python using Python version 3.12.6 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
    (node:83137) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
    gyp info spawn args [
    gyp info spawn args   '/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project//node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project//node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/devicename/.electron-gyp/29.4.6/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/devicename/.electron-gyp/29.4.6',
    gyp info spawn args   '-Dnode_gyp_dir=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/devicename/.electron-gyp/29.4.6/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    Traceback (most recent call last):
      File "/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/node-gyp/gyp/gyp_main.py", line 48, in <module>
        import gyp  # noqa: E402
        ^^^^^^^^^^
      File "/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
        import gyp.input
      File "/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 20, in <module>
        from distutils.version import StrictVersion
    ModuleNotFoundError: No module named 'distutils'
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/node-gyp/lib/configure.js:351:16)
    gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
    gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    gyp ERR! System Darwin 23.6.0
    gyp ERR! command "/Users/devicename/.nvm/versions/node/v18.20.4/bin/node" "/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows/lib/binding/napi-9-darwin-unknown-x64/node-get-windows.node" "--module_name=node-get-windows" "--module_path=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows/lib/binding/napi-9-darwin-unknown-x64" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=9" "--node_napi_label=napi-v9"
    gyp ERR! cwd /Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows
    gyp ERR! node -v v18.20.4
    gyp ERR! node-gyp -v v7.1.2
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/Users/devicename/.nvm/versions/node/v18.20.4/bin/node /Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows/lib/binding/napi-9-darwin-unknown-x64/node-get-windows.node --module_name=node-get-windows --module_path=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows/lib/binding/napi-9-darwin-unknown-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=9 --node_napi_label=napi-v9' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
    node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
    node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
    node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    node-pre-gyp ERR! System Darwin 23.6.0
    node-pre-gyp ERR! command "/Users/devicename/.nvm/versions/node/v18.20.4/bin/node" "/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows
    node-pre-gyp ERR! node -v v18.20.4
    node-pre-gyp ERR! node-pre-gyp -v v1.0.11
    node-pre-gyp ERR! not ok 
error Command failed with exit code 1.
    
                    command=/Users/devicename/.nvm/versions/node/v18.20.4/bin/node /opt/homebrew/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/Users/devicename/Desktop/Workplace/Projects/DesktopApp/electron-project/node_modules/get-windows
error Command failed with exit code 1.

**Comment by sindresorhus** [comment]
Not directly related to this package.
